name: CI
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_SERVER_URL: ${{ secrets.SERVER_URL }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        GITHUB_TOKEN: ${{ secrets.token }}
        BRANCH: gh-pages
        FOLDER: build
