name: Deploy to GitHub Pages
    on:
      push:
        branches:
          - main
    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Build
          run: |
            npm install
            npm run-script build
          env:
            REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}            
